name: quarto-python
channels:
  - conda-forge
dependencies:
  - vl-convert-python=1.0.1
  - altair=5.1.2
  - tabulate=0.9.0
  - quarto=1.5.57
  - python=3.11
  - pandas=2.1.2
  - click=8.1.7
  - pyyaml
  - ipykernel
  - nbformat
  - nbclient
prefix: /Users/victoriafarkas/miniforge3/envs/quarto-python
